export const API_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DEFAULT_RATE_LIMIT_WINDOW_MS: 60_000,
  DEFAULT_RATE_LIMIT_MAX_REQUESTS: 100,
  IP_RATE_LIMIT_MAX_REQUESTS: 60,
  AUTH_RATE_LIMIT_MAX_REQUESTS: 5,
  IDEMPOTENCY_TTL_SECONDS: 86_400,
  REQUEST_ID_HEADER: 'x-request-id',
  IDEMPOTENCY_KEY_HEADER: 'idempotency-key',
  CORRELATION_ID_HEADER: 'x-correlation-id',
} as const;

export const EVENT_CONSTANTS = {
  OUTBOX_BATCH_SIZE: 100,
  OUTBOX_POLL_INTERVAL_MS: 100,
  OUTBOX_IDLE_POLL_INTERVAL_MS: 1000,
  OUTBOX_LOCK_TIMEOUT_MS: 30_000,
  OUTBOX_MAX_PROCESSING_AGE_MS: 300_000,
  OUTBOX_MAX_CONCURRENT: 100,
  OUTBOX_MAX_RETRY_ATTEMPTS: 5,
  OUTBOX_BASE_DELAY_MS: 1000,
  OUTBOX_MAX_DELAY_MS: 60_000,
  OUTBOX_BACKOFF_MULTIPLIER: 2,
  CONSUMER_PREFETCH_COUNT: 1,
  EXCHANGE_NAME: 'erp.events',
} as const;

export const SAGA_CONSTANTS = {
  DEFAULT_MAX_RETRIES: 3,
  DEFAULT_RETRY_DELAY_MS: 60_000,
  DEFAULT_STEP_TIMEOUT_MS: 30_000,
  CLEANUP_BATCH_SIZE: 100,
  COMPLETED_RETENTION_DAYS: 30,
  FAILED_RETENTION_DAYS: 90,
  COMPENSATING_RETENTION_DAYS: 90,
} as const;

export const PLUGIN_CONSTANTS = {
  DEFAULT_HOOK_TIMEOUT_MS: 5000,
  PLUGIN_TABLE_PREFIX: 'plugin_',
} as const;

export const CIRCUIT_BREAKER_CONSTANTS = {
  DEFAULT_FAILURE_THRESHOLD: 5,
  DEFAULT_SUCCESS_THRESHOLD: 3,
  DEFAULT_RESET_TIMEOUT_MS: 30_000,
  DEFAULT_MONITOR_INTERVAL_MS: 60_000,
  DEFAULT_HALF_OPEN_MAX_PROBES: 3,
} as const;

export const CACHE_CONSTANTS = {
  DEFAULT_TTL_SECONDS: 300,
  USER_TTL_SECONDS: 60,
  CONFIG_TTL_SECONDS: 3600,
  LOCK_RETRY_DELAY_MS: 100,
  LOCK_TTL_MS: 5000,
} as const;
